# Generated by Django 4.1.5 on 2023-01-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='data_Added',
            new_name='date_added',
        ),
    ]
